error shown if username or password not given
browserstack/browserstack-cypress-cli pull request #118
Opened 2021-03-02 15:34 UTC by roshan04

If user enters empty password or username then error is thrown during validation

2021-03-03 05:22 UTC, karanshah-browserstack requested changes

2021-03-03 05:22 UTC, karanshah-browserstack commented on bin/helpers/capabilityHelper.js
> +      if(!Utils.isUndefined(args.username) && !Utils.isUndefined(args.key))
What if I don't provide "" in args and set it in browserstack.json. Please consider that case too. 
Also, can you move this validation a bit up? where we already have validation for username and password? https://github.com/browserstack/browserstack-cypress-cli/pull/118/files#diff-26dee8fe62c5e891965d2de49dd74bd0fad786ae2544889d5519d222a6145256R119

2021-03-03 09:30 UTC, karanshah-browserstack requested changes

2021-03-03 09:30 UTC, karanshah-browserstack commented on bin/helpers/zipUpload.js
> +            if(responseData && responseData["error"]){
if (responseData && responseData["error"]) {
    reject(responseData["error"]);
  } else if(resp.statusCode == 401){
    reject(Constants. validationMessages. INVALID_DEFAULT_AUTH_PARAMS);
  }else {
reject(Constants.userMessages.ZIP_UPLOADER_NOT_REACHABLE);
}

2021-03-03 09:50 UTC, karanshah-browserstack approved these changes

2021-03-12 05:27 UTC, prateekbstack commented
LGTM

2021-03-12 15:39 UTC, merged