Add warning around spec count
browserstack/browserstack-cypress-cli pull request #127
Opened 2021-03-16 12:07 UTC by SagarGaniga

2021-03-16 16:42 UTC, suryart requested changes

2021-03-16 16:42 UTC, suryart commented on bin/helpers/utils.js
> +  let expectedCharLength = specFiles.join("").length + 175 * specFiles.length;
What's 175? Can we name it? Maybe from use it from a constant?

2021-03-16 16:42 UTC, suryart commented on bin/helpers/utils.js
> +  let parallels = bsConfig['run_settings']['parallels'];
let's use the `.` instead: `bsConfig.run_settings.parallels`.

2021-03-16 16:42 UTC, suryart commented on bin/helpers/utils.js
> +  let expectedCharLengthPerParallel = expectedCharLength / parallelPerCombination
semicolon? Also, can we ensure that this is going to be an INT and not float?

2021-03-16 17:40 UTC, suryart submitted a review, later dismissed

2021-03-17 06:15 UTC, abhishekchoudhary commented on bin/helpers/constants.js
> +  SPEC_LIMIT_WARNING: "There is a chance that you might not see all the results on the dashboard because of your spec count."
You might not see all your results on the dashboard because of high spec count, please consider reducing the number of spec files in this folder.

2021-03-17 07:11 UTC, suryart approved these changes

2021-03-22 15:49 UTC, prateekbstack commented
LGTM

2021-05-28 09:21 UTC, merged