priting error message while buildartifacts fails
browserstack/browserstack-cypress-cli pull request #194
Opened 2021-12-20 12:34 UTC by roshan04

2021-12-23 06:40 UTC, nagpalkaran95 requested changes

2021-12-23 06:40 UTC, nagpalkaran95 commented on bin/helpers/buildArtifacts.js
> +    try {
why do we need `try` here?

2021-12-23 06:40 UTC, nagpalkaran95 commented on bin/helpers/buildArtifacts.js
please keep indentation same (2 spaces as everyplace else)

2021-12-23 06:40 UTC, nagpalkaran95 commented on bin/helpers/buildArtifacts.js
> +          try {
try inside try? not a good approach. outside try should take care of failures

2021-12-23 06:41 UTC, nagpalkaran95 commented
let's update reporting methods too

2021-12-26 20:02 UTC, nagpalkaran95 requested changes

2021-12-26 20:02 UTC, nagpalkaran95 commented on bin/helpers/utils.js
> -const axios = require("axios");
We need to remove the lib from package.json as well

2021-12-27 05:49 UTC, roshan04 commented on bin/helpers/buildArtifacts.js
> +            logger.error(`Error: Request failed with status code ${resp.statusCode}`)
No had synced with product, we will be just sending the stacktrace to BQ, and for user we will be showing the statuscode.

2021-12-27 05:57 UTC, nagpalkaran95 approved these changes

2021-12-27 06:09 UTC, nagpalkaran95 approved these changes

2021-12-31 07:02 UTC, pranavj1001 commented
Closing this PR on account of https://github.com/browserstack/browserstack-cypress-cli/pull/196

2021-12-31 07:02 UTC, closed without merging