Build stacktace for cli
browserstack/browserstack-cypress-cli pull request #233
Opened 2022-01-25 11:29 UTC by roshan04

2022-01-28 12:38 UTC, nagpalkaran95 requested changes

2022-01-28 12:38 UTC, nagpalkaran95 commented on bin/helpers/downloadBuildStacktrace.js
> +	return new Promise(async (resolve, reject) => {
indentation issue

2022-01-28 15:04 UTC, roshan04 commented on bin/helpers/downloadBuildStacktrace.js
> +	return new Promise(async (resolve, reject) => {
done

2022-01-31 12:49 UTC, nagpalkaran95 commented on bin/helpers/downloadBuildStacktrace.js
> +          reject(err);
should this be `reject(response.statusCode)`?

2022-01-31 14:21 UTC, nagpalkaran95 approved these changes

2022-02-04 09:23 UTC, merged