update: a11y stability changes
browserstack/browserstack-cypress-cli pull request #778
Opened 2024-02-14 14:33 UTC by 07souravkunda

2024-02-19 10:06 UTC, kamal-kaur04 requested changes

2024-02-19 10:06 UTC, kamal-kaur04 commented on bin/accessibility-automation/cypress/index.js
> +            "testRunId": '5058', // variable not consumed, shouldn't matter what we send
This isn't returned in the build start?

2024-02-19 10:06 UTC, kamal-kaur04 commented on bin/accessibility-automation/cypress/index.js
> +Cypress.Commands.add('perfromScan', () => {
```suggestion
Cypress.Commands.add('performScan', () => {
```
maybe?

2024-02-19 10:15 UTC, kamal-kaur04 submitted a review, later dismissed

2024-02-23 08:05 UTC, 07souravkunda commented on bin/accessibility-automation/cypress/index.js
> +    if (!shouldScanTestForAccessibility) return cy.wrap({});
check if shouldScanTestForAccessibility can be replaced

2024-02-23 08:05 UTC, 07souravkunda commented on bin/helpers/capabilityHelper.js
> +    }
add validation for headed

2024-02-23 08:31 UTC, Mirudhula-Nadar commented on bin/helpers/capabilityHelper.js
> +    } else if (browserDetails.version && (!browserDetails.version.includes('latest') || browserDetails.version < 94)) {
@07souravkunda `!browserDetails.version.includes('latest')` it should not have not condition currently its throwing error when we provide any other version like 118, 120

2024-02-23 11:37 UTC, amaanbs approved these changes

2024-02-28 07:44 UTC, asambstack approved these changes

2024-03-01 12:44 UTC, merged