Fix o11y timeouts
browserstack/browserstack-cypress-cli pull request #848
Opened 2024-07-22 04:27 UTC by 07souravkunda

2024-07-23 07:15 UTC, amaanbs requested changes

2024-07-23 07:15 UTC, amaanbs commented on bin/testObservability/helper/helper.js
> +  consoleHolder.log(`[ OBSERVABILITY ] ${text}`);
Do we need this?

2024-07-23 07:15 UTC, amaanbs commented on bin/testObservability/helper/helper.js
> +      consoleHolder.log(response.data.build_hashed_id);
Do we need this?

2024-07-23 07:15 UTC, amaanbs commented on bin/testObservability/helper/requestQueueHandler.js
> +      consoleHolder.log(this.queue.length + " the queue length ");
Do we need this?

2024-07-23 07:15 UTC, amaanbs commented on bin/testObservability/helper/requestQueueHandler.js
> +    require('fs').writeFileSync(require('path').join(__dirname, 'queue.json'), JSON.stringify(this.queue));
Let's rename file `queue.json` to something more meaningful?

2024-07-23 07:15 UTC, amaanbs commented on bin/testObservability/helper/shutdown.js
> +const shutdown = async () => {
Let's rename file & method names to indicate how this shutdown hook is used. Also a comment explaining it's usage.

2024-07-23 07:15 UTC, amaanbs commented on bin/testObservability/reporter/index.js
> +      test.testAnalyticsId = uuidv4()
Needed?

2024-07-23 07:15 UTC, amaanbs commented on bin/testObservability/reporter/index.js
> +const ipc = require('node-ipc');
import needed?

2024-07-23 07:15 UTC, amaanbs commented on bin/testObservability/reporter/index.js
> +        this.ipcServer = server;
Are we using this?

2024-07-23 07:15 UTC, amaanbs commented on bin/testObservability/helper/helper.js
> +exports.nodeRequest = nodeRequest;
Needed?

2024-07-23 07:15 UTC, amaanbs commented on bin/testObservability/helper/helper.js
> +        try {
Needed?

2024-07-23 07:15 UTC, amaanbs commented on bin/testObservability/helper/helper.js
> +const util = require('util');
Unused import

2024-07-23 10:57 UTC, rev-doshi commented on bin/testObservability/helper/requestQueueHandler.js
> +    fs.unlinkSync(path.join(__dirname, PENDING_QUEUES_FILE));
spelling fix PENDING_QUEUES_FILE

2024-07-23 14:30 UTC, amaanbs approved these changes

2024-07-25 07:02 UTC, Baaryan approved these changes

2024-07-26 13:37 UTC, merged