Axios master
browserstack/browserstack-cypress-cli pull request #897
Opened 2024-11-08 10:33 UTC by osho-20

2024-11-08 10:47 UTC, osho-20 commented
@sauravdas1997 can you review once

2024-11-08 11:37 UTC, sauravdas1997 requested changes
- Handling of ATS changes are done by us, this needs to be revisited and tested by ATS team
- Verify the include/exclude tags feature for A11Y

2024-11-08 11:37 UTC, sauravdas1997 commented on test/unit/bin/helpers/reporterHTML.js
> +  // describe('generateCypressBuildReport', () => {
why did we remove test ?

2024-11-08 11:37 UTC, sauravdas1997 commented on bin/testObservability/reporter/index.js
> +        debugOnConsole(`[MOCHA EVENT] EVENT_TEST_BEGIN`);
this looks redundant

2024-11-08 11:37 UTC, sauravdas1997 commented on bin/testObservability/reporter/index.js
> +        debugOnConsole(`[MOCHA EVENT] EVENT_TEST_END`);
Redundant

2024-11-08 11:37 UTC, sauravdas1997 commented on bin/testObservability/reporter/index.js
> +        server.on(IPC_EVENTS.SCREENSHOT, this.cypressScreenshotListener.bind(this));
did we test screenshots in o11y ?

2024-11-08 11:37 UTC, sauravdas1997 commented on bin/testObservability/crashReporter/index.js
> +module.exports = CrashReporter;
EOF

2024-11-08 11:37 UTC, sauravdas1997 commented on bin/helpers/atsHelper.js
> +}
EOF

2024-11-08 11:37 UTC, sauravdas1997 commented on bin/helpers/atsHelper.js
> +const path = require('path');
is ATS Tested ?

2024-11-08 11:37 UTC, sauravdas1997 commented on bin/commands/runs.js
> +        }
These are ATS related handling, this needs to be verified by ATS team

2024-11-08 11:37 UTC, sauravdas1997 commented on bin/accessibility-automation/cypress/index.js
> +});
EOF

2024-11-08 11:44 UTC, osho-20 commented on bin/testObservability/reporter/index.js
> +        server.on(IPC_EVENTS.SCREENSHOT, this.cypressScreenshotListener.bind(this));
yes

2024-11-11 06:25 UTC, sauravdas1997 approved these changes

2024-11-19 06:46 UTC, closed without merging